# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]
env: 
  KEY: "Ddd"
  # STRAPI_EC2_PRIVATE_KEY: ${{ secrets.STRAPI_EC2_PRIVATE_KEY }}
  # STRAPI_EC2_USERNAME: ${{ secrets.STRAPI_EC2_USERNAME }}
  # STRAPI_EC2_HOSTNAME: ${{ secrets.STRAPI_EC2_HOSTNAME }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # - name: Build and deploy strapi
    #   run: |
    #     ls
    #     mkdir test
    #     echo "test txt" > test/abc.txt
    #     mkdir -p scripts
    #     ls
    #     echo "$STRAPI_EC2_PRIVATE_KEY" > scripts/key.pem
    #     chmod 600 scripts/key.pem
    #     scp -o 'StrictHostKeyChecking no' -i ./scripts/key.pem -r test/ $STRAPI_EC2_USERNAME@$STRAPI_EC2_HOSTNAME:~/delete
    #     echo "copied files"
              
